package bean;
// Generated 06/09/2022 15:59:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produtos generated by hbm2java
 */
@Entity
@Table(name="produtos"
    ,catalog="mpv"
)
public class Produtos  implements java.io.Serializable {


     private int idprodutos;
     private Grupo grupo;
     private String nome;
     private BigDecimal valorUnitario;
     private Set vendasProdutoses = new HashSet(0);

    public Produtos() {
    }

	
    public Produtos(int idprodutos) {
        this.idprodutos = idprodutos;
    }
    public Produtos(int idprodutos, Grupo grupo, String nome, BigDecimal valorUnitario, Set vendasProdutoses) {
       this.idprodutos = idprodutos;
       this.grupo = grupo;
       this.nome = nome;
       this.valorUnitario = valorUnitario;
       this.vendasProdutoses = vendasProdutoses;
    }
   
     @Id 

    
    @Column(name="idprodutos", unique=true, nullable=false)
    public int getIdprodutos() {
        return this.idprodutos;
    }
    
    public void setIdprodutos(int idprodutos) {
        this.idprodutos = idprodutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grupo")
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }

    
    @Column(name="nome", length=60)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="valorUnitario", precision=10)
    public BigDecimal getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(BigDecimal valorUnitario) {
        this.valorUnitario = valorUnitario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produtos")
    public Set getVendasProdutoses() {
        return this.vendasProdutoses;
    }
    
    public void setVendasProdutoses(Set vendasProdutoses) {
        this.vendasProdutoses = vendasProdutoses;
    }




}


