package bean;
// Generated 06/09/2022 15:59:02 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servicos generated by hbm2java
 */
@Entity
@Table(name="servicos"
    ,catalog="mpv"
)
public class Servicos  implements java.io.Serializable {


     private int idservicos;
     private String nome;
     private BigDecimal valor;
     private String ativo;

    public Servicos() {
    }

	
    public Servicos(int idservicos) {
        this.idservicos = idservicos;
    }
    public Servicos(int idservicos, String nome, BigDecimal valor, String ativo) {
       this.idservicos = idservicos;
       this.nome = nome;
       this.valor = valor;
       this.ativo = ativo;
    }
   
     @Id 

    
    @Column(name="idservicos", unique=true, nullable=false)
    public int getIdservicos() {
        return this.idservicos;
    }
    
    public void setIdservicos(int idservicos) {
        this.idservicos = idservicos;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="valor", precision=10)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    
    @Column(name="ativo", length=1)
    public String getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(String ativo) {
        this.ativo = ativo;
    }




}


