package bean;
// Generated 06/09/2022 15:59:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VendasProdutosId generated by hbm2java
 */
@Embeddable
public class VendasProdutosId  implements java.io.Serializable {


     private int idvendas;
     private int produto;

    public VendasProdutosId() {
    }

    public VendasProdutosId(int idvendas, int produto) {
       this.idvendas = idvendas;
       this.produto = produto;
    }
   


    @Column(name="idvendas", nullable=false)
    public int getIdvendas() {
        return this.idvendas;
    }
    
    public void setIdvendas(int idvendas) {
        this.idvendas = idvendas;
    }


    @Column(name="produto", nullable=false)
    public int getProduto() {
        return this.produto;
    }
    
    public void setProduto(int produto) {
        this.produto = produto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendasProdutosId) ) return false;
		 VendasProdutosId castOther = ( VendasProdutosId ) other; 
         
		 return (this.getIdvendas()==castOther.getIdvendas())
 && (this.getProduto()==castOther.getProduto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdvendas();
         result = 37 * result + this.getProduto();
         return result;
   }   


}


